export const USER_LOGIN = "USER_LOGIN"; 
export const REGISTER_LOGIN = "REGISTER_LOGIN";
export const UPLOAD_DATASET = "UPLOAD_DATASET";
export const USER_DETAILS = "USER_DETAILS";
export const TABLE_DATA = "TABLE_DATA";
export const SELECTED_DATA = "SELECTED_DATA";